# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/index.html'
    weight: 10
  - name: Project
    url: '#news'
    weight: 20
  - name: Experience
    url: '#group'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Resume
    url: "https://caihanlin.com/file/CV-HanlinCAI.pdf"